//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PluginsSystem.ObjectModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBUsersPermision
    {
        public int ID { get; set; }
        public System.Guid UserID { get; set; }
        public System.Guid PluginID { get; set; }
        public int Premissions { get; set; }
    
        public virtual DBPlugin DBPlugin { get; set; }
        public virtual DBUser DBUser { get; set; }
    }
}
