//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PluginsSystem.ObjectModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBUser
    {
        public DBUser()
        {
            this.DBUsersPermisions = new HashSet<DBUsersPermision>();
        }
    
        public System.Guid ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<DBUsersPermision> DBUsersPermisions { get; set; }
    }
}
